framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    delay: 1000
                    max_retries: 4
                    multiplier: 3
            failed: 'doctrine://messenger?queue_name=failed'
            sync: 'sync://'
            high_priority:
                dsn: 'doctrine://messenger?queue_name=high_priority'
                retry_strategy:
                    delay: 1000
                    max_retries: 4
                    multiplier: 3
            low_priority:
                dsn: 'doctrine://messenger?queue_name=low_priority'
                retry_strategy:
                    delay: 2000
                    max_retries: 4
                    multiplier: 3

        failure_transport: failed

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - 'App\Messenger\Middleware\PriorityMiddleware'
                    - 'App\Messenger\Middleware\LoggingMiddleware'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Messenger\Message\GetSingleConferenceQuery: sync
            App\Messenger\Message\MatchVolunteerMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
